<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
		<RootNamespace>TcNo_Acc_Switcher_Client</RootNamespace>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
		<ApplicationIcon>favicon.ico</ApplicationIcon>
		<Version>2025.11.20.03</Version>
		<Authors>TroubleChute (Wesley Pyburn)</Authors>
		<Product>TcNo Account Switcher</Product>
		<Copyright>Copyright © TroubleChute (Wesley Pyburn) 2019-2025</Copyright>
		<PackageProjectUrl>https://github.com/TCNOCo/TcNo-Acc-Switcher</PackageProjectUrl>
		<PackageIcon>TcNoAccSw-Icon-100x100.png</PackageIcon>
		<RepositoryUrl>https://github.com/TCNOCo/TcNo-Acc-Switcher</RepositoryUrl>
		<AssemblyName>TcNo-Acc-Switcher</AssemblyName>
		<AssemblyVersion>2025.11.20.03</AssemblyVersion>
		<Platforms>x64</Platforms>
		<PlatformTarget>x64</PlatformTarget>
		<SignAssembly>false</SignAssembly>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<AnalysisLevel>6.0</AnalysisLevel>
		<!--<SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>-->
		<RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
		<NoWarn>$(NoWarn);MSB3277</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
		<!--<PublishTrimmed>true</PublishTrimmed>-->
		<PublishSingleFile>true</PublishSingleFile>
		<EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
		<!-- Prevent trimming of WPF/WinForms logic that might be used via reflection -->
		<!--<TrimMode>partial</TrimMode>-->
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CefSharp.Common" Version="143.0.90" />
		<PackageReference Include="CefSharp.Wpf.NETCore" Version="143.0.90">
			<NoWarn>NU1701</NoWarn>
		</PackageReference>
		<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3650.58">
			<NoWarn>MSB3277</NoWarn>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\TcNo-Acc-Switcher-Server\TcNo-Acc-Switcher-Server.csproj">
			<EmbedInteropTypes>false</EmbedInteropTypes>
		</ProjectReference>
		<ProjectReference Include="..\TcNo-Acc-Switcher-Tray\TcNo-Acc-Switcher-Tray.csproj" />
		<ProjectReference Include="..\TcNo-Acc-Switcher-Updater\TcNo-Acc-Switcher-Updater.csproj">
			<Private>true</Private>
			<CopyLocalSatelliteAssemblies>true</CopyLocalSatelliteAssemblies>
		</ProjectReference>
		<ProjectReference Include="..\TcNo-Acc-Switcher-Installer\TcNo-Acc-Switcher-Installer.csproj">
			<ReferenceOutputAssembly>false</ReferenceOutputAssembly>
		</ProjectReference>
		<ProjectReference Include="..\TcNo-Acc-Switcher-Wrapper\TcNo-Acc-Switcher-Wrapper.csproj">
			<ReferenceOutputAssembly>false</ReferenceOutputAssembly>
		</ProjectReference>
	</ItemGroup>

	<ItemGroup>
		<None Update="inc\TcNo-Acc-Switcher.runtimeconfig.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Include="..\.editorconfig" Link=".editorconfig" />
		<None Include="..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\TcNo-Acc-Switcher-Server\wwwroot\img\TcNoAccSw-Icon-100x100.png">
			<Pack>True</Pack>
			<PackagePath></PackagePath>
		</None>
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="PostBuild.bat $(Configuration) $(ProjectDir)" IgnoreExitCode="true" />
	</Target>

	<ItemGroup>
		<PackageReference Update="chromiumembeddedframework.runtime.win-arm64" Version="143.0.9" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Update="chromiumembeddedframework.runtime.win-x64" Version="143.0.9" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Update="chromiumembeddedframework.runtime.win-x86" Version="143.0.9" />
	</ItemGroup>

</Project>
