name: Public GitHub build

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: "Description:"
        default: "Manual build from source"

jobs:
  build:
    runs-on: windows-latest
    steps:

    - name: Get current date
      id: date
      run: echo "date=$(Get-Date -Format 'yyyy-MM-dd')" >> $env:GITHUB_OUTPUT
      shell: pwsh

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore TcNo-Acc-Switcher-Client\TcNo-Acc-Switcher-Client.csproj --runtime win-x64
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

    - name: Build Debug
      run: dotnet build TcNo-Acc-Switcher-Client\TcNo-Acc-Switcher-Client.csproj --configuration Debug --no-restore

    - name: Build Release
      run: dotnet build TcNo-Acc-Switcher-Client\TcNo-Acc-Switcher-Client.csproj --configuration Release --no-restore

    - name: Upload Debug Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.date.outputs.date }} Debug
        path: TcNo-Acc-Switcher-Client\bin\Debug\net9.0-windows

    - name: Upload Release Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.date.outputs.date }} Release
        path: TcNo-Acc-Switcher-Client\bin\Release\net9.0-windows
